name: 'Build, Grype and Syft'
description: | 
  Generates a Docker image locally which will then be SBOM'd and scanned. 
  The SBOM will be scanned and then the image will be scanned to ensure as clean an image as possible.
branding:
  icon: layers
  color: purple
inputs:
  image-name:
    description: "The name of the image to build."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Local Container
      uses: docker/build-push-action@v4
      id: local-build
      with:
        tags: "local/${{ inputs.image-name }}:latest"
        push: false
        load: true

    - name: Create SBOM
      uses: anchore/sbom-action@v0
      id: create-sbom
      with:
        image: local/cloud-cli-tools:latest
        format: spdx-json
        output-file: "${{ inputs.image-name }}-sbom.spdx.json"

    - name: Scan SBOM
      uses: anchore/scan-action@v3
      id: scan-sbom
      with:
        sbom: "${{ inputs.image-name }}-sbom.spdx.json"
        fail-build: true
        severity-cutoff: critical
        output-format: json

    - name: Upload SBOM Scan Results
      uses: actions/upload-artifact@v3
      id: upload-sbom-scan-artifact
      with:
        name: "${{ inputs.image-name }}-sbom-results.json"
        path: "results.json"

    - name: Scan image
      uses: anchore/scan-action@v3
      id: scan-container
      with:
        image: "local/${{ inputs.image-name }}:latest"
        fail-build: true
        severity-cutoff: critical
        output-format: json

    - name: Upload Container Scan Results
      uses: actions/upload-artifact@v3
      id: upload-artifact
      with:
        name: "${{ inputs.image-name }}-scan-results.json"
        path: "results.json"
